GET http://localhost:8080/books
Authorization: Bearer ACCESS_TOKEN
###

POST http://localhost:8080/books
Content-Type: application/json

{
    "id" : "4",
    "title": "The Godfather",
    "author": "Mario Puzo"
}

###
DELETE http://localhost:8080/books/4

###
POST http://localhost:8080/login